>>> ####  Customer Satisfaction prediction

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
print("libraries imported")

libraries imported

In [2]:
df = pd.read_csv("cust_satisfaction.csv")
# df.head()

In [3]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [5]:
df.head(7)

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
5,Female,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,26,1180,1,4,1,0,0.0
6,Male,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,47,1276,2,4,2,9,23.0

In [6]:
df.tail(7)

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
103897,Female,Loyal Customer,Business travel,Business,satisfied,60,1599,4,4,4,9,7.0
103898,Male,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,50,1620,2,4,2,0,0.0
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [ ]:
file_path = "https://raw.githubusercontent.com/upflairs-pvt-ltd/1st_june_data_science/refs/heads/master/customer_satisfaction/cust_satisfaction.csv"
df = pd.read_csv(file_path)
df.head()

In [ ]:
## assignment 
### google spreadsheet

In [7]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103904 non-null  object
 1   Customer Type               103904 non-null  object
 2   Type of Travel              103904 non-null  object
 3   Class                       103904 non-null  object
 4   satisfaction                103904 non-null  object
 5   Age                         103904 non-null  int64
 6   Flight Distance             103904 non-null  int64
 7   Inflight entertainment      103904 non-null  int64
 8   Baggage handling            103904 non-null  int64
 9   Cleanliness                 103904 non-null  int64
 10  Departure Delay in Minutes  103904 non-null  int64
 11  Arrival Delay in Minutes    103594 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 9.5+ MB

In [14]:
df['Gender'].value_counts()

Gender
Female    52651
Male      51081
Name: count, dtype: int64

In [10]:
df.duplicated().sum()

172

In [11]:
df.drop_duplicates(inplace=True)  # to delete duplicate rows

In [12]:
df.duplicated().sum()

0

In [ ]:
# df['Type of Travel']

In [15]:
df['Type of Travel'].value_counts()

Type of Travel
Business travel    71521
Personal Travel    32211
Name: count, dtype: int64

In [16]:
df['Class'].value_counts()

Class
Business    49555
Eco         46684
Eco Plus     7493
Name: count, dtype: int64

In [17]:
df['Customer Type'].value_counts()

Customer Type
Loyal Customer       84778
disloyal Customer    18954
Name: count, dtype: int64

In [18]:
df['Gender'].value_counts()

Gender
Female    52651
Male      51081
Name: count, dtype: int64

In [19]:
male = df[df['Gender'] == "Male"]
female = df[df['Gender'] == "Female"]

In [20]:
male

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
6,Male,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,47,1276,2,4,2,9,23.0
9,Male,disloyal Customer,Business travel,Eco,neutral or dissatisfied,20,1061,2,4,2,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103896,Male,Loyal Customer,Business travel,Eco,neutral or dissatisfied,57,867,4,3,4,0,0.0
103898,Male,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,50,1620,2,4,2,0,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [21]:
female

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
5,Female,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,26,1180,1,4,1,0,0.0
7,Female,Loyal Customer,Business travel,Business,satisfied,52,2035,5,5,4,4,0.0
8,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,41,853,1,1,2,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103893,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,58,296,3,3,1,0,29.0
103895,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,24,1055,1,5,1,13,10.0
103897,Female,Loyal Customer,Business travel,Business,satisfied,60,1599,4,4,4,9,7.0
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0

In [22]:
male["Customer Type"].value_counts()

Customer Type
Loyal Customer       42384
disloyal Customer     8697
Name: count, dtype: int64

In [23]:
female["Customer Type"].value_counts()

Customer Type
Loyal Customer       42394
disloyal Customer    10257
Name: count, dtype: int64

In [24]:
male['satisfaction'].value_counts()

satisfaction
neutral or dissatisfied    28647
satisfied                  22434
Name: count, dtype: int64

In [25]:
female['satisfaction'].value_counts()

satisfaction
neutral or dissatisfied    30171
satisfied                  22480
Name: count, dtype: int64

In [27]:
df['satisfaction'].value_counts()

satisfaction
neutral or dissatisfied    58818
satisfied                  44914
Name: count, dtype: int64

In [28]:
df['satisfaction'].value_counts(normalize=True)

satisfaction
neutral or dissatisfied    0.567019
satisfied                  0.432981
Name: proportion, dtype: float64

In [29]:
df['satisfaction'].value_counts(normalize=True) * 100

satisfaction
neutral or dissatisfied    56.701886
satisfied                  43.298114
Name: proportion, dtype: float64

In [ ]:
male_with_4plus_rating = male[male["Inflight entertainment"]>=4]
male_with_4plus_rating.shape

In [ ]:
# 22k satisfied 
# 27k 4+ rating

In [ ]:
# EDA

In [ ]:
df['Inflight entertainment'].value_counts()

In [31]:
df.isnull().sum()

Gender                          0
Customer Type                   0
Type of Travel                  0
Class                           0
satisfaction                    0
Age                             0
Flight Distance                 0
Inflight entertainment          0
Baggage handling                0
Cleanliness                     0
Departure Delay in Minutes      0
Arrival Delay in Minutes      310
dtype: int64

In [32]:
df.shape

(103732, 12)

In [33]:
df.dropna(inplace=True)  # to delete missing rows

In [34]:
df.isnull().sum()

Gender                        0
Customer Type                 0
Type of Travel                0
Class                         0
satisfaction                  0
Age                           0
Flight Distance               0
Inflight entertainment        0
Baggage handling              0
Cleanliness                   0
Departure Delay in Minutes    0
Arrival Delay in Minutes      0
dtype: int64

In [35]:
df.shape

(103422, 12)

In [36]:
df.drop_duplicates(inplace=True)

In [39]:
df['Customer Type'].unique()

array(['Loyal Customer', 'disloyal Customer'], dtype=object)

In [40]:
df

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,23,192,2,4,2,3,0.0
103900,Male,Loyal Customer,Business travel,Business,satisfied,49,2347,5,5,4,0,0.0
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,30,1995,4,4,4,7,14.0
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied,22,1000,1,1,1,0,0.0
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied,27,1723,1,4,1,0,0.0

In [41]:
# x and y  
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [42]:
onhe_hote_encoder = OneHotEncoder(drop='first')

In [43]:
df.head(10)

,Gender,Customer Type,Type of Travel,Class,satisfaction,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied,13,460,5,4,5,25,18.0
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied,25,235,1,3,1,1,6.0
2,Female,Loyal Customer,Business travel,Business,satisfied,26,1142,5,4,5,0,0.0
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,25,562,2,3,2,11,9.0
4,Male,Loyal Customer,Business travel,Business,satisfied,61,214,3,4,3,0,0.0
5,Female,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,26,1180,1,4,1,0,0.0
6,Male,Loyal Customer,Personal Travel,Eco,neutral or dissatisfied,47,1276,2,4,2,9,23.0
7,Female,Loyal Customer,Business travel,Business,satisfied,52,2035,5,5,4,4,0.0
8,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied,41,853,1,1,2,0,0.0
9,Male,disloyal Customer,Business travel,Eco,neutral or dissatisfied,20,1061,2,4,2,0,0.0

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103422 entries, 0 to 103903
Data columns (total 12 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Gender                      103422 non-null  object
 1   Customer Type               103422 non-null  object
 2   Type of Travel              103422 non-null  object
 3   Class                       103422 non-null  object
 4   satisfaction                103422 non-null  object
 5   Age                         103422 non-null  int64
 6   Flight Distance             103422 non-null  int64
 7   Inflight entertainment      103422 non-null  int64
 8   Baggage handling            103422 non-null  int64
 9   Cleanliness                 103422 non-null  int64
 10  Departure Delay in Minutes  103422 non-null  int64
 11  Arrival Delay in Minutes    103422 non-null  float64
dtypes: float64(1), int64(6), object(5)
memory usage: 10.3+ MB

In [45]:
cat_col=df.select_dtypes(include="O")

In [46]:
cat_col

,Gender,Customer Type,Type of Travel,Class,satisfaction
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied
2,Female,Loyal Customer,Business travel,Business,satisfied
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied
4,Male,Loyal Customer,Business travel,Business,satisfied
...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied
103900,Male,Loyal Customer,Business travel,Business,satisfied
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied

In [47]:
# cat_col = df.select_dtypes(include="O")
num_col = df.select_dtypes(exclude="O")

# transform_df = onhe_hote_encoder.fit_transform(cat_col)

In [55]:
num_col

,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,13,460,5,4,5,25,18.0
1,25,235,1,3,1,1,6.0
2,26,1142,5,4,5,0,0.0
3,25,562,2,3,2,11,9.0
4,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...
103899,23,192,2,4,2,3,0.0
103900,49,2347,5,5,4,0,0.0
103901,30,1995,4,4,4,7,14.0
103902,22,1000,1,1,1,0,0.0
103903,27,1723,1,4,1,0,0.0

In [56]:
onhe_hote_encoder.fit(cat_col)

OneHotEncoder(drop='first')

In [57]:
transform_df = onhe_hote_encoder.transform(cat_col)

In [58]:
transform_df = transform_df.toarray()
# transform_df

In [59]:
transform_df.shape

(103422, 6)

In [60]:
transform_df

array([[1., 0., 1., 0., 1., 0.],
       [1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       ...,
       [1., 1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [79]:
# transform_df.shape

In [62]:
# transform_df

In [63]:
# list(onhe_hote_encoder.get_feature_names_out())

In [64]:
# list(onhe_hote_encoder.get_feature_names_out())

In [65]:
one_hot_data = pd.DataFrame(transform_df,columns=list(onhe_hote_encoder.get_feature_names_out()))
one_hot_data

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus,satisfaction_satisfied
0,1.0,0.0,1.0,0.0,1.0,0.0
1,1.0,1.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,1.0
3,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...
103417,0.0,1.0,0.0,1.0,0.0,0.0
103418,1.0,0.0,0.0,0.0,0.0,1.0
103419,1.0,1.0,0.0,0.0,0.0,0.0
103420,0.0,1.0,0.0,1.0,0.0,0.0
103421,1.0,0.0,0.0,0.0,0.0,0.0

In [66]:
cat_col.head()

,Gender,Customer Type,Type of Travel,Class,satisfaction
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied
2,Female,Loyal Customer,Business travel,Business,satisfied
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied
4,Male,Loyal Customer,Business travel,Business,satisfied

In [67]:
### applying one hot encoding with the help of pandas 
# one_hot_data_pandas = pd.get_dummies(cat_col,drop_first=True).astype(int)
# one_hot_data_pandas.head()

In [80]:
cat_col

,Gender,Customer Type,Type of Travel,Class,satisfaction
0,Male,Loyal Customer,Personal Travel,Eco Plus,neutral or dissatisfied
1,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied
2,Female,Loyal Customer,Business travel,Business,satisfied
3,Female,Loyal Customer,Business travel,Business,neutral or dissatisfied
4,Male,Loyal Customer,Business travel,Business,satisfied
...,...,...,...,...,...
103899,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied
103900,Male,Loyal Customer,Business travel,Business,satisfied
103901,Male,disloyal Customer,Business travel,Business,neutral or dissatisfied
103902,Female,disloyal Customer,Business travel,Eco,neutral or dissatisfied
103903,Male,Loyal Customer,Business travel,Business,neutral or dissatisfied

In [81]:
num_col

,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,13,460,5,4,5,25,18.0
1,25,235,1,3,1,1,6.0
2,26,1142,5,4,5,0,0.0
3,25,562,2,3,2,11,9.0
4,61,214,3,4,3,0,0.0
...,...,...,...,...,...,...,...
103899,23,192,2,4,2,3,0.0
103900,49,2347,5,5,4,0,0.0
103901,30,1995,4,4,4,7,14.0
103902,22,1000,1,1,1,0,0.0
103903,27,1723,1,4,1,0,0.0

In [82]:
pd.concat([one_hot_data,num_col],axis=1)

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus,satisfaction_satisfied,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1.0,0.0,1.0,0.0,1.0,0.0,13.0,460.0,5.0,4.0,5.0,25.0,18.0
1,1.0,1.0,0.0,0.0,0.0,0.0,25.0,235.0,1.0,3.0,1.0,1.0,6.0
2,0.0,0.0,0.0,0.0,0.0,1.0,26.0,1142.0,5.0,4.0,5.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,25.0,562.0,2.0,3.0,2.0,11.0,9.0
4,1.0,0.0,0.0,0.0,0.0,1.0,61.0,214.0,3.0,4.0,3.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
103899,NaN,NaN,NaN,NaN,NaN,NaN,23.0,192.0,2.0,4.0,2.0,3.0,0.0
103900,NaN,NaN,NaN,NaN,NaN,NaN,49.0,2347.0,5.0,5.0,4.0,0.0,0.0
103901,NaN,NaN,NaN,NaN,NaN,NaN,30.0,1995.0,4.0,4.0,4.0,7.0,14.0
103902,NaN,NaN,NaN,NaN,NaN,NaN,22.0,1000.0,1.0,1.0,1.0,0.0,0.0
103903,NaN,NaN,NaN,NaN,NaN,NaN,27.0,1723.0,1.0,4.0,1.0,0.0,0.0

In [83]:
# one_hot_data_pandas  
# num_col  
complete_df = pd.concat([one_hot_data,num_col],axis=1)
complete_df.head()

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus,satisfaction_satisfied,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1.0,0.0,1.0,0.0,1.0,0.0,13.0,460.0,5.0,4.0,5.0,25.0,18.0
1,1.0,1.0,0.0,0.0,0.0,0.0,25.0,235.0,1.0,3.0,1.0,1.0,6.0
2,0.0,0.0,0.0,0.0,0.0,1.0,26.0,1142.0,5.0,4.0,5.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,25.0,562.0,2.0,3.0,2.0,11.0,9.0
4,1.0,0.0,0.0,0.0,0.0,1.0,61.0,214.0,3.0,4.0,3.0,0.0,0.0

In [84]:
complete_df.dtypes

Gender_Male                        float64
Customer Type_disloyal Customer    float64
Type of Travel_Personal Travel     float64
Class_Eco                          float64
Class_Eco Plus                     float64
satisfaction_satisfied             float64
Age                                float64
Flight Distance                    float64
Inflight entertainment             float64
Baggage handling                   float64
Cleanliness                        float64
Departure Delay in Minutes         float64
Arrival Delay in Minutes           float64
dtype: object

In [70]:
# complete_df

In [86]:
complete_df.drop("satisfaction_satisfied",axis=1)

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1.0,0.0,1.0,0.0,1.0,13.0,460.0,5.0,4.0,5.0,25.0,18.0
1,1.0,1.0,0.0,0.0,0.0,25.0,235.0,1.0,3.0,1.0,1.0,6.0
2,0.0,0.0,0.0,0.0,0.0,26.0,1142.0,5.0,4.0,5.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,25.0,562.0,2.0,3.0,2.0,11.0,9.0
4,1.0,0.0,0.0,0.0,0.0,61.0,214.0,3.0,4.0,3.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
103899,NaN,NaN,NaN,NaN,NaN,23.0,192.0,2.0,4.0,2.0,3.0,0.0
103900,NaN,NaN,NaN,NaN,NaN,49.0,2347.0,5.0,5.0,4.0,0.0,0.0
103901,NaN,NaN,NaN,NaN,NaN,30.0,1995.0,4.0,4.0,4.0,7.0,14.0
103902,NaN,NaN,NaN,NaN,NaN,22.0,1000.0,1.0,1.0,1.0,0.0,0.0
103903,NaN,NaN,NaN,NaN,NaN,27.0,1723.0,1.0,4.0,1.0,0.0,0.0

In [88]:
###  splitting  
# x  and y  
x = complete_df.drop("satisfaction_satisfied",axis=1)
x.head()

,Gender_Male,Customer Type_disloyal Customer,Type of Travel_Personal Travel,Class_Eco,Class_Eco Plus,Age,Flight Distance,Inflight entertainment,Baggage handling,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes
0,1.0,0.0,1.0,0.0,1.0,13.0,460.0,5.0,4.0,5.0,25.0,18.0
1,1.0,1.0,0.0,0.0,0.0,25.0,235.0,1.0,3.0,1.0,1.0,6.0
2,0.0,0.0,0.0,0.0,0.0,26.0,1142.0,5.0,4.0,5.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,25.0,562.0,2.0,3.0,2.0,11.0,9.0
4,1.0,0.0,0.0,0.0,0.0,61.0,214.0,3.0,4.0,3.0,0.0,0.0

In [89]:
y = complete_df[['satisfaction_satisfied']]
y.head()

   satisfaction_satisfied
0                     0.0
1                     0.0
2                     1.0
3                     0.0
4                     1.0

In [90]:
x['Customer Type_disloyal Customer'].isnull().sum()

480

In [91]:
x.isnull().sum()

Gender_Male                        480
Customer Type_disloyal Customer    480
Type of Travel_Personal Travel     480
Class_Eco                          480
Class_Eco Plus                     480
Age                                480
Flight Distance                    480
Inflight entertainment             480
Baggage handling                   480
Cleanliness                        480
Departure Delay in Minutes         480
Arrival Delay in Minutes           480
dtype: int64

In [74]:
from sklearn.model_selection import train_test_split

In [75]:
x_train,x_test,y_train,y_test =  train_test_split(x,y,test_size=0.2,random_state=21)

In [76]:
### Model selection ==> Model Training 
from sklearn.linear_model import LogisticRegression

In [77]:
lgr = LogisticRegression()

In [78]:
### model training 
lgr.fit(x_train,y_train)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

#### Model evaluation

In [ ]:
print("Training score : ",round(lgr.score(x_train,y_train) * 100 ,2))
print("Testing score : ",round(lgr.score(x_test,y_test) * 100 ,2))

In [ ]:
from sklearn.metrics  import confusion_matrix

In [ ]:
# confusion_matrix(actual,predicted ) 
y_pred = lgr.predict(x_test)

In [ ]:
# y_pred   <=== predicted 
# y_test   <=== actual

In [ ]:
matrix  = confusion_matrix(y_test,y_pred ) 
matrix

In [ ]:
y_test['predicted'] = y_pred   # adding a new predicted column  with actual value

In [ ]:
# y_test.head(40) 
matrix

In [ ]:
9651+2092+2028+6914

In [ ]:
y_test.shape

In [ ]:
y_test.head(40)

In [ ]:
lgr.score(x_test,y_test['satisfaction_satisfied'])  # test data

In [ ]:
matrix   # test data

In [ ]:
(9651+6914)/(9651+6914+2092+2028)

In [ ]:
x_train.shape   #   x

In [ ]:
y_train.shape

In [ ]:
## imbalance or balance  
y_train.value_counts(normalize=True)

In [ ]:
from sklearn.metrics import classification_report ,accuracy_score,precision_score,recall_score,f1_score

# precision_score()
# 9651 +  2092  
# matrix  
6914 +  2028

In [ ]:
x_train.columns

In [ ]:
# classification_report(actual,prediction) 
print(classification_report(y_test["satisfaction_satisfied"],y_test['predicted']))

In [ ]:
y_test['predicted'].value_counts()

In [ ]:
import seaborn as sns 
import matplotlib.pyplot as plt

In [ ]:
sns.heatmap(matrix,annot=True,fmt='d',cmap='crest',) 
plt.axis('off')
plt.show()

In [ ]:
y_pred = lgr.predict(x_test)

In [ ]:
y_pred[:10]

In [ ]:
y_pred2 = lgr.predict_proba(x_test)  # probability 0 - 1

In [ ]:
threshold =   0.5 >=    ==>   1 
                              0

In [ ]:
pd.options.display.float_format = "{:,.2f}".format

In [ ]:
y_pred2[:10]

In [ ]:
import warnings 
warnings.filterwarnings('ignore')

In [ ]:
# batch prediction  
# sinlge data point 
unseen_data_point = [[1,0,1,0,1,42,500,5,5,5,0,0]]  
single_prediction = lgr.predict(unseen_data_point)
print(single_prediction[0])
if single_prediction[0] == 1:
    print("your passenger was satisfied with airline service")
else:
    print("your passenger was not satisfied with airline service")

### Model save

In [ ]:
import joblib , pickle

In [ ]:
st = "upflairs" 
type(st)

In [ ]:
st = str('upflairs')
type(st)

In [ ]:
joblib.dump(lgr,'logistic_regrssion.lb')

In [ ]:
joblib.dump()

In [ ]:
onehote , pandas

In [ ]:
#loading the model 
model = joblib.load('logistic_regrssion.lb')
model

In [ ]:
unseen_data_point = [[1,0,1,0,1,42,500,5,5,5,0,0]]  
single_prediction = model.predict(unseen_data_point)
print(single_prediction[0])
if single_prediction[0] == 1:
    print("your passenger was satisfied with airline service")
else:
    print("your passenger was not satisfied with airline service")

In [ ]:
x_train.columns